export const TeachingMediums = [
  'bangla medium',
  'english medium',
  'english version',
  'admission test',
  'specialized learning',
] as const;

export const DaysOfWeek = [
  'Sat',
  'Sun',
  'Mon',
  'Tue',
  'Wed',
  'Thu',
  'Fri',
] as const;

// 🎓 নতুন এবং স্পেসিফিক টিচিং ক্লাস লিস্ট
export const TeachingClasses = [
  'Nursery',
  'KG-1',
  'KG-2',
  'Class 1',
  'Class 2',
  'Class 3',
  'Class 4',
  'Class 5',
  'Class 6',
  'Class 7',
  'Class 8',
  'Class 9',
  'SSC',
  'HSC 1st Year',
  'HSC 2nd Year',
  'A-Level(AS)',
  'A-Level(A2)',
  'Dhaka University Admission',
  'BUET Admission',
  'Medical Admission',
  'Private University Admission',
] as const;

// 📚 Specialized Learning এর জন্য আলাদা ক্লাস/সাবজেক্ট লিস্ট
export const SpecializedLearningClasses = [
  'Quran Learning',
  'Bangla Language Learning',
  'English Language Learning',
  'French Language Learning',
] as const;

// 🕌 মাদ্রাসা মিডিয়ামের ক্লাস লিস্ট
export const MadrasaClasses = [
  'Nursery',
  'Class 1',
  'Class 2',
  'Class 3',
  'Class 4',
  'Class 5',
  'Class 6',
  'Class 7',
  'Class 8',
  'Class 9',
  'দাখিল / SSC',
  'আলিম HSC 1st',
  'আলিম HSC 2nd',
] as const;

export const BachelorMajors = [
  'Computer Science & Engineering (CSE)',
  'Information and Communication Technology (ICT)',
  'Electrical and Electronic Engineering (EEE)',
  'Civil Engineering',
  'Mechanical Engineering',
  'Biomedical Engineering',
  'Architecture',
  'Environmental Science',
  'Physics',
  'Chemistry',
  'Mathematics',
  'Statistics',
  'Biotechnology & Genetic Engineering',
  'Microbiology',
  'Food & Nutrition Science',
  'MBBS',
  'BDS',
  'Pharmacy',
  'Nursing',
  'Physiotherapy',
  'Medical Laboratory Technology',
  'Public Health',
  'Business Administration (BBA)',
  'Economics',
  'Accounting & Finance',
  'Marketing',
  'Management',
  'HRM (Human Resource Management)',
  'Supply Chain Management',
  'International Business',
  'Banking & Insurance',
  'Tourism & Hospitality',
  'English',
  'Bangla',
  'History',
  'Philosophy',
  'Islamic Studies',
  'Sociology',
  'Fine Arts',
  'Music',
  'Political Science',
  'Mass Communication',
  'Law',
  'Criminology',
  'Education',
  'Agriculture',
  'Other (Enter Manually)',
] as const;
